/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhispersRouteImport } from './routes/whispers'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomSlugRouteImport } from './routes/room.$slug'

const WhispersRoute = WhispersRouteImport.update({
  id: '/whispers',
  path: '/whispers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomSlugRoute = RoomSlugRouteImport.update({
  id: '/room/$slug',
  path: '/room/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/creator': typeof CreatorRoute
  '/lobby': typeof LobbyRoute
  '/profile': typeof ProfileRoute
  '/whispers': typeof WhispersRoute
  '/room/$slug': typeof RoomSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/creator': typeof CreatorRoute
  '/lobby': typeof LobbyRoute
  '/profile': typeof ProfileRoute
  '/whispers': typeof WhispersRoute
  '/room/$slug': typeof RoomSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/creator': typeof CreatorRoute
  '/lobby': typeof LobbyRoute
  '/profile': typeof ProfileRoute
  '/whispers': typeof WhispersRoute
  '/room/$slug': typeof RoomSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/creator'
    | '/lobby'
    | '/profile'
    | '/whispers'
    | '/room/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/creator'
    | '/lobby'
    | '/profile'
    | '/whispers'
    | '/room/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/creator'
    | '/lobby'
    | '/profile'
    | '/whispers'
    | '/room/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CreatorRoute: typeof CreatorRoute
  LobbyRoute: typeof LobbyRoute
  ProfileRoute: typeof ProfileRoute
  WhispersRoute: typeof WhispersRoute
  RoomSlugRoute: typeof RoomSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whispers': {
      id: '/whispers'
      path: '/whispers'
      fullPath: '/whispers'
      preLoaderRoute: typeof WhispersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$slug': {
      id: '/room/$slug'
      path: '/room/$slug'
      fullPath: '/room/$slug'
      preLoaderRoute: typeof RoomSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CreatorRoute: CreatorRoute,
  LobbyRoute: LobbyRoute,
  ProfileRoute: ProfileRoute,
  WhispersRoute: WhispersRoute,
  RoomSlugRoute: RoomSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
